name: 'Download all release assets'
description: 'Download all release assets. It supports GitHub Enterprise.'
author: 'Chris Burkert (https://github.com/cb80)'
inputs:
  tag:
    description: 'Tag name'
    required: true
  to:
    description: 'Target directory'
    required: false
    default: '.'
  repo:
    description: 'Owner/Repository of the release'
    required: false
    default: ${{ github.repository }}
  token:
    description: 'GitHub token, default: secrets.GITHUB_TOKEN'
    required: false
    default: ${{ github.token }}
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'box'
  color: 'blue'
