---
name: CI/CD

on:
  pull_request: {}
  push:
    branches:
    - main
    tags:
    - v*

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up node16
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Run npm
      run: npm install && npm run all

    - name: create tag for test release
      run: |
        git tag -f ghatest
        git push -f origin ghatest

    - name: create test release without assets
      uses: cb80/pubrel@latest
      with:
        ref: 'refs/tags/ghatest'
        replace: ghatest

    - name: create test release with assets
      uses: cb80/pubrel@latest
      with:
        ref: 'refs/tags/ghatest'
        replace: ghatest
        files: |
          README.md
          .git/index

    - name: download assets
      uses: ./
      with:
        tag: ghatest
        to: dl

    - name: compare assets
      run: |
        ls -al dl/
        cmp README.md dl/README.md
        cmp .git/index dl/index

    - name: remove test release
      uses: cb80/delrel@latest
      with:
        tag: ghatest

    - name: remove tag for test release
      run: git push origin :ghatest

    - name: Update latest tag when pushing to main
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: |
        git tag -f latest
        git push -f origin latest

    - name: Publish myself
      if: ${{ github.event_name == 'push' }}
      uses: cb80/pubrel@latest
      with:
        replace: latest
